version: "3"

services:
  postgres-jaffle_shop-dev:
    image: postgres:15.1
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaffle_shop
    volumes:
      - postgres-jaffle_shop-dev:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "user",
          "-d",
          "jaffle_shop"
        ]
      interval: 5s
      retries: 20
    restart: always
  postgres-jaffle_shop-prod:
    image: postgres:15.1
    ports:
      - 55433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaffle_shop
    volumes:
      - postgres-jaffle_shop-prod:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "user",
          "-d",
          "jaffle_shop"
        ]
      interval: 5s
      retries: 20
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.17
    depends_on:
      postgres-jaffle_shop-dev:
        condition: service_healthy
      postgres-jaffle_shop-prod:
        condition: service_healthy
    ports:
      - 9999:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost/misc/ping || exit 1"
        ]
      interval: 20s
      retries: 20
    restart: always
volumes:
  pgadmin:
  postgres-jaffle_shop-dev:
  postgres-jaffle_shop-prod:
